---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: adguard
  namespace: kube-system
spec:
  repo: https://k8s-at-home.com/charts/
  chart: adguard-home
  targetNamespace: default
  valuesContent: |-
    affinity: &aff
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - nixkube
    persistence:
      config:
        enabled: true
        storageClass: local-path
    service:
      dns-tcp:
        type: LoadBalancer
      dns-udp:
        type: LoadBalancer
    ingress:
      main:
        enabled: true
        hosts:
          - host: adguard.vanderpot.net
            paths:
              - path: /
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: default-secured@kubernetescrd