---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: adguard
  namespace: kube-system
spec:
  repo: https://k8s-at-home.com/charts/
  chart: adguard-home
  targetNamespace: default
  valuesContent: |-
    affinity: &aff
      nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - nixkube
    persistence:
      config:
        enabled: true
        storageClass: local-path
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: esphome
  namespace: kube-system
spec:
  repo: https://k8s-at-home.com/charts/
  chart: esphome
  targetNamespace: default
  valuesContent: |-
    persistence:
      config:
        enabled: true
        storageClass: local-path
    ingress:
      main:
        enabled: true
        hosts:
          - host: esphome.vanderpot.net
            paths:
              - path: /
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: default-auth@kubernetescrd
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: homeassistant
  namespace: kube-system
spec:
  repo: https://k8s-at-home.com/charts/
  chart: home-assistant
  targetNamespace: default
  valuesContent: |-
    persistence:
      config:
        enabled: true
        storageClass: local-path
    ingress:
      main:
        enabled: true
        hosts:
          - host: hass.vanderpot.net
            paths:
              - path: /
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: default-auth@kubernetescrd
    securityContext:
      privileged: true
    affinity: &aff
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - nixkube
    mariadb:
      enabled: true
      persistence:
        enabled: true
        storageClass: local-path
      affinity: *aff
    influxdb:
      enabled: true
      persistence:
        enabled: true
        storageClass: local-path
      affinity: *aff
    addons:
      codeserver:
        enabled: true
        volumeMounts:
          - name: config
            mountPath: /config
        ingress:
          enabled: true
          hosts:
            - host: config.hass.vanderpot.net
              paths:
                - path: /
          annotations:
            traefik.ingress.kubernetes.io/router.middlewares: default-auth@kubernetescrd
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: mosquitto
  namespace: kube-system
spec:
  repo: https://k8s-at-home.com/charts/
  chart: mosquitto
  targetNamespace: default
  valuesContent: |-
    configmap:
      configinc:
        enabled: true
        name: 
        data:
          mosquitto.conf: ""
    persistence:
      configinc:
        enabled: true
        type: configMap
        #todo: hack
        name: mosquitto-configinc
    affinity: &aff
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - nixkube
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mosquitto.route
  namespace: default
spec:
  entryPoints:
    - mqtt
  routes:
    - match: HostSNI(`*`)
      services:
        - name: mosquitto
          port: 1883
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: thelounge
  namespace: kube-system
spec:
  repo: https://k8s-at-home.com/charts/
  chart: thelounge
  targetNamespace: default
  valuesContent: |-
    persistence:
      config:
        enabled: true
        storageClass: local-path
    ingress:
      main:
        enabled: true
        hosts:
          - host: irc.vanderpot.net
            paths:
              - path: /
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nodered
  namespace: kube-system
spec:
  repo: https://k8s-at-home.com/charts/
  chart: node-red
  targetNamespace: default
  valuesContent: |-
    persistence:
      data:
        enabled: true
        storageClass: local-path
        accessMode: ReadWriteOnce
        size: 32Gi
    ingress:
      main:
        enabled: true
        hosts:
          - host: nodered.vanderpot.net
            paths:
              - path: /
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: default-auth@kubernetescrd
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ser2sock
  namespace: kube-system
spec:
  repo: https://k8s-at-home.com/charts/
  chart: ser2sock
  targetNamespace: default
  valuesContent: |-
    image:
      tag: armhf
    securityContext:
      privileged: true
    service:
      main:
        enabled: true
        type: NodePort
        ports:
          server:
            nodePort: 30208
    persistence:
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/ttyUSB0
        # hostPathType: CharDevice
    affinity: &aff
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - zgateway
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ytdl
  namespace: kube-system
spec:
  repo: https://k8s-at-home.com/charts/
  chart: youtubedl-material
  targetNamespace: default
  valuesContent: |-
    ingress:
      main:
        enabled: true
        hosts:
          - host: ytdl.vanderpot.net
            paths:
              - path: /
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: default-auth@kubernetescrd
    persistence:
      config:
        enabled: true
        storageClass: local-path
      audio:
        enabled: true
        type: hostPath
        hostPath: /zfs/home/kube/ytdl/audio
      subscriptions:
        enabled: true
        type: hostPath
        hostPath: /zfs/home/kube/ytdl/subscriptions
      users:
        enabled: true
        type: hostPath
        hostPath: /zfs/home/kube/ytdl/users
      video:
        enabled: true
        type: hostPath
        hostPath: /zfs/home/kube/ytdl/video
    affinity: &aff
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - nixkube
---
