---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: thelounge
  namespace: kube-system
spec:
  repo: https://k8s-at-home.com/charts/
  chart: thelounge
  targetNamespace: default
  valuesContent: |-
    persistence:
      config:
        enabled: true
        storageClass: local-path
    ingress:
      main:
        enabled: true
        hosts:
          - host: irc.vanderpot.net
            paths:
              - path: /
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ytdl
  namespace: kube-system
spec:
  repo: https://k8s-at-home.com/charts/
  chart: youtubedl-material
  targetNamespace: default
  valuesContent: |-
    ingress:
      main:
        enabled: true
        hosts:
          - host: ytdl.vanderpot.net
            paths:
              - path: /
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: default-auth@kubernetescrd
    persistence:
      config:
        enabled: true
        storageClass: local-path
      audio:
        enabled: true
        type: hostPath
        hostPath: /zfs/home/kube/ytdl/audio
      subscriptions:
        enabled: true
        type: hostPath
        hostPath: /zfs/home/kube/ytdl/subscriptions
      users:
        enabled: true
        type: hostPath
        hostPath: /zfs/home/kube/ytdl/users
      video:
        enabled: true
        type: hostPath
        hostPath: /zfs/home/kube/ytdl/video
    affinity: &aff
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - nixkube
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: torrent-alex
  namespace: kube-system
spec:
  repo: https://k8s-at-home.com/charts/
  chart: deluge
  targetNamespace: default
  valuesContent: |-
    ingress:
      main:
        enabled: true
        hosts:
          - host: dl1.vanderpot.net
            paths:
              - path: /
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: default-auth@kubernetescrd
    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /zfs/home/alex/config
      downloads:
        enabled: true
        type: hostPath
        hostPath: /zfs/home/alex/data
    service:
      bt:
        enabled: true
        primary: false
        type: NodePort
        ports:
          tcp:
            enabled: true
            protocol: TCP
            port: 30102
            nodePort: 30102
            targetPort: 30102
          udp:
            enabled: true
            protocol: UDP
            port: 30102
            nodePort: 30102
            targetPort: 30102
    affinity: &aff
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - nixkube
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: torrent
  namespace: kube-system
spec:
  repo: https://k8s-at-home.com/charts/
  chart: deluge
  targetNamespace: default
  valuesContent: |-
    ingress:
      main:
        enabled: true
        hosts:
          - host: dl.vanderpot.net
            paths:
              - path: /
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: default-auth@kubernetescrd
    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /zfs/home/torrent/config
      downloads:
        enabled: true
        type: hostPath
        hostPath: /zfs/home/torrent/data
    service:
      bt:
        enabled: true
        primary: false
        type: NodePort
        ports:
          tcp:
            enabled: true
            protocol: TCP
            port: 30101
            nodePort: 30101
            targetPort: 30101
          udp:
            enabled: true
            protocol: UDP
            port: 30101
            nodePort: 30101
            targetPort: 30101
    affinity: &aff
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - nixkube
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: dashboard
  namespace: kube-system
spec:
  repo: https://kubernetes.github.io/dashboard/
  chart: kubernetes-dashboard
  targetNamespace: default
  valuesContent: |-
    ingress:
      enabled: true
      hosts:
        - kube.vanderpot.net
      paths:
        - /
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: default-auth@kubernetescrd
    extraArgs:
      - --enable-skip-login
      - --disable-settings-authorizer
    rbac:
      create: true
      clusterReadOnlyRole: true
---
