---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: thelounge
  namespace: kube-system
spec:
  repo: https://k8s-at-home.com/charts/
  chart: thelounge
  targetNamespace: default
  valuesContent: |-
    persistence:
      config:
        enabled: true
        storageClass: local-path
    ingress:
      main:
        enabled: true
        hosts:
          - host: irc.vanderpot.net
            paths:
              - path: /
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ytdl
  namespace: kube-system
spec:
  repo: https://k8s-at-home.com/charts/
  chart: youtubedl-material
  targetNamespace: default
  valuesContent: |-
    ingress:
      main:
        enabled: true
        hosts:
          - host: ytdl.vanderpot.net
            paths:
              - path: /
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: default-auth@kubernetescrd
    persistence:
      config:
        enabled: true
        storageClass: local-path
      audio:
        enabled: true
        type: hostPath
        hostPath: /zfs/home/kube/ytdl/audio
      subscriptions:
        enabled: true
        type: hostPath
        hostPath: /zfs/home/kube/ytdl/subscriptions
      users:
        enabled: true
        type: hostPath
        hostPath: /zfs/home/kube/ytdl/users
      video:
        enabled: true
        type: hostPath
        hostPath: /zfs/home/kube/ytdl/video
    affinity: &aff
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - nixkube
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: torrent-alex
  namespace: kube-system
spec:
  repo: https://k8s-at-home.com/charts/
  chart: deluge
  targetNamespace: default
  valuesContent: |-
    ingress:
      main:
        enabled: true
        hosts:
          - host: dl1.vanderpot.net
            paths:
              - path: /
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: default-auth@kubernetescrd
    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /zfs/home/alex/config
      downloads:
        enabled: true
        type: hostPath
        hostPath: /zfs/home/alex/data
    service:
      bt:
        enabled: true
        primary: false
        type: LoadBalancer
        externalTrafficPolicy: Local
        ports:
          tcp:
            enabled: true
            protocol: TCP
            port: 30102
            nodePort: 30102
            targetPort: 30102
          udp:
            enabled: true
            protocol: UDP
            port: 30102
            nodePort: 30102
            targetPort: 30102
    affinity: &aff
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - nixkube
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rtorrent
  namespace: kube-system
spec:
  repo: https://k8s-at-home.com/charts/
  chart: rtorrent-flood
  targetNamespace: default
  valuesContent: |-
    env:
      FLOOD_OPTION_AUTH: none
      FLOOD_OPTION_RTSOCKET: /config/.local/share/rtorrent/rtorrent.sock
    podSecurityContext:
      runAsUser: 1000
    service:
      bt:
        enabled: true
        primary: false
        type: NodePort
        externalTrafficPolicy: Local
        ports:
          tcp:
            enabled: true
            protocol: TCP
            port: 30104
            nodePort: 30104
            targetPort: 30104
          udp:
            enabled: true
            protocol: UDP
            port: 30104
            nodePort: 30104
            targetPort: 30104
    ingress:
      main:
        enabled: true
        hosts:
          - host: dl2.vanderpot.net
            paths:
              - path: /
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: default-auth@kubernetescrd
    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /zfs/home/torrent/config/rtorrent
        mountPath: /config
      downloads:
        enabled: true
        type: hostPath
        hostPath: /bulk/home/torrent/data
        mountPath: /downloads
    affinity: &aff
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - nixkube
    config: |
      session.use_lock.set = no
      method.insert = cfg.basedir,  private|const|string, (cat,(fs.homedir),"/.local/share/rtorrent/")
      method.insert = cfg.download, private|const|string, (cat,"/downloads/","download/")
      method.insert = cfg.logs,     private|const|string, (cat,(cfg.download),"log/")
      method.insert = cfg.logfile,  private|const|string, (cat,(cfg.logs),"rtorrent-",(system.time),".log")
      method.insert = cfg.session,  private|const|string, (cat,(cfg.basedir),".session/")
      method.insert = cfg.watch,    private|const|string, (cat,(cfg.download),"watch/")
      fs.mkdir.recursive = (cat,(cfg.basedir))
      fs.mkdir = (cat,(cfg.download))
      fs.mkdir = (cat,(cfg.logs))
      fs.mkdir = (cat,(cfg.session))
      fs.mkdir = (cat,(cfg.watch))
      fs.mkdir = (cat,(cfg.watch),"/load")
      fs.mkdir = (cat,(cfg.watch),"/start")
      schedule2 = watch_load, 11, 10, ((load.verbose, (cat, (cfg.watch), "load/*.torrent")))
      schedule2 = watch_start, 10, 10, ((load.start_verbose, (cat, (cfg.watch), "start/*.torrent")))
      dht.add_bootstrap = dht.transmissionbt.com:6881
      dht.add_bootstrap = dht.libtorrent.org:25401

      # Maximum number of simultaneous downloads and uploads slots (global slots!) (`max_downloads_global`, `max_uploads_global`)
      throttle.max_downloads.global.set = 3000
      throttle.max_uploads.global.set   = 3000
      
      # Maximum and minimum number of peers to connect to per torrent while downloading (`min_peers`, `max_peers`) Default: `100` and `200` respectively
      throttle.min_peers.normal.set = 256
      throttle.max_peers.normal.set = 1024
      
      # Same as above but for seeding completed torrents (seeds per torrent), `-1` for same as downloading (`min_peers_seed`, `max_peers_seed`) Default: `-1` for both
      throttle.min_peers.seed.set = 32
      throttle.max_peers.seed.set = 128
      
      # Maximum number of simultaneous downloads and uploads slots per torrent (`max_uploads`) Default: `50` for both
      throttle.max_downloads.set = 512
      throttle.max_uploads.set = 512
      trackers.numwant.set = 256
      network.port_range.set = 30104-30104
      network.max_open_files.set = 16384
      network.max_open_sockets.set = 32748
    
      network.receive_buffer.size.set = 128M
      network.send_buffer.size.set    = 128M
    
      pieces.memory.max.set = 8192M
      session.path.set = (cat, (cfg.session))
      directory.default.set = (cat, (cfg.download))
      log.execute = (cat, (cfg.logs), "execute.log")
      encoding.add = utf8
      system.daemon.set = true
      system.umask.set = 0002
      system.cwd.set = (directory.default)
      network.http.max_open.set = 50
      network.http.dns_cache_timeout.set = 25
      network.scgi.open_local = (cat,(cfg.basedir),rtorrent.sock)
      print = (cat, "Logging to ", (cfg.logfile))
      log.open_file = "log", (cfg.logfile)
      log.add_output = "info", "log"
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: dashboard
  namespace: kube-system
spec:
  repo: https://kubernetes.github.io/dashboard/
  chart: kubernetes-dashboard
  targetNamespace: default
  valuesContent: |-
    ingress:
      enabled: true
      hosts:
        - kube.vanderpot.net
      paths:
        - /
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: default-auth@kubernetescrd
    extraArgs:
      - --enable-skip-login
      - --disable-settings-authorizer
    rbac:
      create: true
      clusterReadOnlyRole: true
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: radarr
  namespace: kube-system
spec:
  repo: https://k8s-at-home.com/charts/
  chart: radarr
  targetNamespace: default
  valuesContent: |-
    ingress:
      main:
        enabled: true
        hosts:
          - host: radarr.vanderpot.net
            paths:
              - path: /
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: default-auth@kubernetescrd
    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /zfs/home/torrent/config/radarr
      media:
        enabled: true
        type: hostPath
        hostPath: /zfs/home/torrent/data
    affinity: &aff
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - nixkube
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: sonarr
  namespace: kube-system
spec:
  repo: https://k8s-at-home.com/charts/
  chart: sonarr
  targetNamespace: default
  valuesContent: |-
    ingress:
      main:
        enabled: true
        hosts:
          - host: sonarr.vanderpot.net
            paths:
              - path: /
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: default-auth@kubernetescrd
    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /zfs/home/torrent/config/sonarr
      media:
        enabled: true
        type: hostPath
        hostPath: /zfs/home/torrent/data
    affinity: &aff
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - nixkube
---
