apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: torrent-alex
  namespace: kube-system
spec:
  repo: https://k8s-at-home.com/charts/
  chart: deluge
  targetNamespace: default
  valuesContent: |-
    additionalContainers:
      exporter:
        name: exporter
        image: tobbez/deluge_exporter:latest
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: deluge-exporter-env
        env:
          - name: DELUGE_HOST
            value: "{{.Release.Name}}-deluge-rpc"
          - name: DELUGE_PORT
            value: "58846"
        ports:
          - name: exporter
            containerPort: 9354
            protocol: TCP
    ingress:
      main:
        enabled: true
        hosts:
          - host: dl1.vanderpot.net
            paths:
              - path: /
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: default-auth@kubernetescrd
    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /zfs/home/alex/config
      downloads:
        enabled: true
        type: hostPath
        hostPath: /bulk/home/alex/data
    service:
      metrics:
        enabled: true
        primary: false
        type: ClusterIP
        ports:
          metrics:
            enabled: true
            protocol: TCP
            port: 9354
            targetPort: 9354
      rpc:
        enabled: true
        primary: false
        type: NodePort
        ports:
          rpc:
            enabled: true
            protocol: TCP
            port: 58846
            targetPort: 58846
            nodePort: 30846
      bt:
        enabled: true
        primary: false
        type: NodePort
        externalTrafficPolicy: Local
        ports:
          tcp:
            enabled: true
            protocol: TCP
            port: 30102
            nodePort: 30102
            targetPort: 30102
          udp:
            enabled: true
            protocol: UDP
            port: 30102
            nodePort: 30102
            targetPort: 30102
    affinity: &aff
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - nixkube
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: deluge
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: torrent-alex
      app.kubernetes.io/name: deluge
  endpoints:
    - port: metrics