apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: fooddata
  namespace: kube-system
spec:
  repo: https://charts.platy.plus
  chart: hasura
  targetNamespace: default
  valuesContent: |-
    postgresql:
      enabled: true
      postgresqlDatabase: postgres
      postgresqlPassword: postgrespassword
      image:
        tag: 12
    global:
      ingress:
        enabled: true
        domain: vanderpot.net
    ingress:
      enabled: true
      subdomain: food
      className: ""
    devMode: true
    console:
      enabled: true
    adminSecret: ilikefood123 # sue me
    affinity: &aff
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - nixkube