---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: hassapps
  namespace: default
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: HostRegexp(`{subdomain:[a-z]+}.vanderpot.net`)
      kind: Rule
      services:
        - name: homeassistant
          port: 80
      priority: 1
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: udm
  namespace: default
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`unifi.vanderpot.net`)
      kind: Rule
      services:
        - name: udmpro
          port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: default
spec:
  externalName: 10.10.10.107
  type: ExternalName
  ports:
    - protocol: TCP
      port: 80
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: udmpro
  namespace: default
spec:
  externalName: 10.10.10.1
  type: ExternalName
  ports:
    - protocol: TCP
      port: 443
      name: https

