---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: esphome
  namespace: kube-system
spec:
  repo: https://k8s-at-home.com/charts/
  chart: esphome
  targetNamespace: default
  valuesContent: |-
    persistence:
      config:
        enabled: true
        storageClass: local-path
    ingress:
      main:
        enabled: true
        hosts:
          - host: esphome.vanderpot.net
            paths:
              - path: /
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: default-auth@kubernetescrd
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: homeassistant
  namespace: kube-system
spec:
  repo: https://k8s-at-home.com/charts/
  chart: home-assistant
  targetNamespace: default
  valuesContent: |-
    persistence:
      config:
        enabled: true
        storageClass: local-path
    ingress:
      main:
        enabled: true
        hosts:
          - host: hass.vanderpot.net
            paths:
              - path: /
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: default-auth@kubernetescrd
    securityContext:
      privileged: true
    affinity: &aff
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - nixkube
    mariadb:
      enabled: true
      persistence:
        enabled: true
        storageClass: local-path
      affinity: *aff
    influxdb:
      enabled: true
      persistence:
        enabled: true
        storageClass: local-path
      affinity: *aff
    addons:
      codeserver:
        enabled: true
        volumeMounts:
          - name: config
            mountPath: /config
        ingress:
          enabled: true
          hosts:
            - host: hassconfig.vanderpot.net
              paths:
                - path: /
          annotations:
            traefik.ingress.kubernetes.io/router.middlewares: default-auth@kubernetescrd
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nodered
  namespace: kube-system
spec:
  repo: https://k8s-at-home.com/charts/
  chart: node-red
  targetNamespace: default
  valuesContent: |-
    persistence:
      data:
        enabled: true
        storageClass: local-path
        accessMode: ReadWriteOnce
        size: 32Gi
    ingress:
      main:
        enabled: true
        hosts:
          - host: nodered.vanderpot.net
            paths:
              - path: /
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: default-auth@kubernetescrd
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ser2sock
  namespace: kube-system
spec:
  repo: https://k8s-at-home.com/charts/
  chart: ser2sock
  targetNamespace: default
  valuesContent: |-
    image:
      tag: armhf
    securityContext:
      privileged: true
    service:
      main:
        enabled: true
        type: NodePort
        ports:
          server:
            nodePort: 30208
    persistence:
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/ttyUSB0
        # hostPathType: CharDevice
    affinity: &aff
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - zgateway
---