---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: lancache
  namespace: kube-system
spec:
  repo: https://k8s-at-home.com/charts/
  chart: lancache
  targetNamespace: default
  valuesContent: |-
    env:
      CACHE_MODE: monolithic
      CACHE_DISK_SIZE: 8388608m
    persistence:
      data:
        enabled: true
        type: hostPath
        hostPath: /bulk/home/kube/lancache
    ingress:
      main:
        enabled: true
        hosts:
          - host: lancache.vanderpot.net
            paths:
              - path: /
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: cache
  namespace: default
spec:
  routes:
    - match: HostRegexp(`{host:.+}`)
      kind: Rule
      services:
        - name: lancache
          port: 80
      middlewares:
        - name: cache-ipwhitelist
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cache-ipwhitelist
spec:
  ipWhiteList:
    sourceRange:
      - 10.10.10.16/28
      - 10.10.10.32/27
      - 10.10.10.64/26
      - 10.10.10.128/25
      - 10.10.11.0/24