apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: mosquitto
  namespace: kube-system
spec:
  repo: https://k8s-at-home.com/charts/
  chart: mosquitto
  targetNamespace: default
  valuesContent: |-
    service:
      main:
        type: LoadBalancer
    configmap:
      configinc:
        enabled: true
        name: 
        data:
          mosquitto.conf: ""
    persistence:
      configinc:
        enabled: true
        type: configMap
        #todo: hack
        name: mosquitto-configinc
    affinity: &aff
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - nixkube