apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nfs
  namespace: kube-system
spec:
  chart: nfs-subdir-external-provisioner
  repo: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
  targetNamespace: kube-system
  set:
    nfs.server: 10.10.10.99
    nfs.path: /zfs/home/kube
    storageClass.name: nfs