apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: sourceforts
  namespace: kube-system
spec:
  repo: https://k8s-at-home.com/charts/
  chart: nullserv
  targetNamespace: default
  valuesContent: |-
    controller:
      replicas: 1
    probes:
      readiness:
        enabled: false
      liveness:
        enabled: false
      startup:
        custom: true
        spec:
          tcpSocket:
            port: 30115
          timeoutSeconds: 1
          periodSeconds: 60
          successThreshold: 1
          failureThreshold: 10
    image:
      repository: gusnaughton/sfclassic
      tag: v1
      imagePullPolicy: Always
    env:
      GAME_ARGS: "+maxplayers 16 -port 30115 +map sf_astrodome -tickrate 66 +log on"
      GAME_PORT: "30115"
      SRCDS_PORT: "30115"
      CLIENT_PORT: 30108
      STEAM_USER_DIR: /data
    service:
      main:
        type: NodePort
        externalTrafficPolicy: Local
        ports:
          http:
            enabled: false
          https:
            enabled: false 
          rcon:
            enabled: true
            protocol: TCP
            port: 30115
            nodePort: 30115
            targetPort: 30115
          game:
            enabled: true
            protocol: UDP
            port: 30115
            nodePort: 30115
            targetPort: 30115
    configmap:
      config:
        enabled: true
        data:
          phase_build.cfg: |
            hostname "[aVo] Team Avolition (US West) [BUILD]"
          phase_combat.cfg: |
            hostname "[aVo] Team Avolition (US West) [COMBAT]"
          admins.cfg: |
            Admins
            {
              "gustopher"
              {
                "auth" "steam"
                "identity" "STEAM_0:1:35061356"
                "flags" "abcdefghijklmnopqrst"
              }
              "ajvpot"
              {
                "auth" "steam"
                "identity" "STEAM_0:1:37954437"
                "flags" "abcdefghijklmnopqrst"
              }
              "Sirenfal"
              {
                "auth" "steam"
                "identity" "STEAM_0:0:14902516"
                "flags" "abcdefghijklmnopqrst"
              }
              "Storm_Surge"
              {
                "auth" "steam"
                "identity" "STEAM_0:0:3118159"
                "flags" "abcdefghijklmnopqrst"
              }
            }
    persistence:
      data:
        enabled: true
        storageClass: local-path
        mountPath: /data
        accessMode: ReadWriteOnce
        size: 256Gi
        skipuninstall: true
        skipUninstall: true
      configbuild:
        enabled: true
        type: configMap
        subPath: phase_build.cfg
        mountPath: /data/sfclassic/cfg/phase_build.cfg
        name: "{{.Release.Name}}-nullserv-config"
      configcombat:
        enabled: true
        type: configMap
        subPath: phase_combat.cfg
        mountPath: /data/sfclassic/cfg/phase_combat.cfg
        name: "{{.Release.Name}}-nullserv-config"
      admins:
        enabled: true
        type: configMap
        subPath: admins.cfg
        mountPath: /data/sfclassic/addons/sourcemod/configs/admins.cfg
        name: "{{.Release.Name}}-nullserv-config"
    affinity: &aff
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - nixkube
