apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      websecure:
        tls:
          enabled: true
          certResolver: letsencrypt
    persistence:
      enabled: true
      name: data
      path: /data
      storageClassName: local-path
    additionalArguments:
      - "--providers.kubernetescrd.allowexternalnameservices=true"
      - "--providers.kubernetescrd.allowcrossnamespace=true"
      - "--providers.kubernetesingress.allowexternalnameservices=true"
      - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=alex@vanderpot.com"
      
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      
      - "--entrypoints.websecure.http.middlewares=default-auth@kubernetescrd"
      # LetsEncrypt Staging
      #- "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: auth
  namespace: default
spec:
  basicAuth:
    secret: authsecret