apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      websecure:
        tls:
          enabled: true
          certResolver: letsencrypt
          domains:
            - main: k8s.vanderpot.net
              sans:
                - hass.vanderpot.net
                - unifi.vanderpot.net
                - sso.vanderpot.net
    persistence:
      enabled: true
      name: data
      path: /data
      storageClassName: local-path
    additionalArguments:
      - "--providers.kubernetescrd.allowexternalnameservices=true"
      - "--providers.kubernetesingress.allowexternalnameservices=true"
      - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=alex@vanderpot.com"
      # LetsEncrypt Staging
      #- "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
