apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ingressRoute:
      dashboard:
        enabled: false
    deployment:
      kind: DaemonSet
      dnsPolicy: ClusterFirstWithHostNet
    service:
      enabled: false
    hostNetwork: true
    securityContext:
      capabilities:
        add:
          - NET_BIND_SERVICE
      runAsNonRoot: false
      runAsUser: 0
    envFrom:
      - configMapRef:
          name: traefik-env
    ports:
      metrics:
        expose: true
        port: 9001
        exposedPort: 9001
      traefik:
        port: 9002
      web:
        port: 80
      websecure:
        port: 443
        tls:
          enabled: true
    additionalArguments:
      - "--providers.kubernetescrd.allowexternalnameservices=true"
      - "--providers.kubernetescrd.allowcrossnamespace=true"
      - "--providers.kubernetesingress.allowexternalnameservices=true"    
      - "--serverstransport.insecureskipverify=true"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: secured
spec:
  chain:
    middlewares:
      - name: https-only
      - name: auth
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: https-only
  namespace: default
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: auth
  namespace: default
spec:
  forwardAuth:
    address: http://traefik-forward-auth.keycloak.svc.cluster.local:4181
    trustForwardHeader: true
    authResponseHeaders:
      - X-Forwarded-User
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  repo: https://charts.jetstack.io
  chart: cert-manager
  targetNamespace: kube-system
  valuesContent: |-
    installCRDs: true
    prometheus:
      servicemonitor:
        enabled: true
---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: traefikmonitor
  namespace: kube-system
  labels:
    release: prometheus
    app: prometheus-traefik
spec:
  endpoints:
    - path: /metrics
      port: metrics
  jobLabel: traefik-metrics
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/instance: traefik
      app.kubernetes.io/name: traefik

