version: '3.1'

services:
  octoprint:
    image: octoprint/octoprint
    restart: unless-stopped
    ports:
      - "80:80"
    privileged: true
    #volumes:
    # - /octoprint:/octoprint
    # uncomment the lines below to ensure camera streaming is enabled when
    # you add a video device
    #environment:
    #  - ENABLE_MJPG_STREAMER=false
    #deploy:
    #  placement:
    #    constraints:
    #      - node.hostname == threedprint
    labels:
      kompose.service.expose: "print.vanderpot.net"