version: "3.1"

services:
#  flood:
#    image: jesec/flood
#    user: 1000:1001
#    restart: unless-stopped
#    command: --port 3001 --allowedpath /data --auth none --rtsocket ~/.local/share/rtorrent/rtorrent.sock
#    environment:
#      HOME: /config
#    volumes:
#      - /zfs/home/torrent/config:/config
#      - /zfs/home/torrent/data:/data
#    ports:
#      - 3001:3001
#    deploy: *masterOnly
#    labels:
#      kompose.volume.type: hostPath
#
#  rtorrent:
#    deploy: *masterOnly
#    image: jesec/rtorrent
#    user: 1000:1001
#    tty: true
#    restart: unless-stopped
#    command: -o network.port_range.set=6881-6881,system.daemon.set=true
#    environment:
#      HOME: /config
#    volumes:
#      - /zfs/home/torrent/config:/config
#      - /zfs/home/torrent/data:/data
#    ports:
#      - 6881:6881
#    labels:
#      kompose.volume.type: hostPath

  radarr:
    deploy: &masterOnly
      placement:
        constraints:
          - node.hostname == nixkube
    restart: unless-stopped
    ports:
      - "7878"
    volumes:
      - /zfs/home/torrent/config:/config
      - /zfs/home/torrent/data:/data
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=America/New_York
    image: linuxserver/radarr
    labels:
      kompose.service.expose: "media.vanderpot.net/radarr"
      kompose.volume.type: hostPath

  sonarr:
    deploy: *masterOnly
    restart: unless-stopped
    ports:
      - "7878"
    volumes:
      - /zfs/home/torrent/config:/config
      - /zfs/home/torrent/data:/data
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=America/New_York
    image: linuxserver/sonarr
    labels:
      kompose.service.expose: "media.vanderpot.net/sonarr"
      kompose.volume.type: hostPath

