# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: Azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}


    - name: Generate
      run: ./generate.sh
    # todo switch bake to helm intall for rollback/delete
    - uses: azure/k8s-bake@v1
      with:
        renderEngine: 'helm'
        helmChart: './compose/seedbox/'
        helm-version: 'latest' 
      id: bake_seedbox
    - uses: azure/k8s-bake@v1
      with:
        renderEngine: 'helm'
        helmChart: './compose/octoprint/'
        helm-version: 'latest'
      id: bake_octoprint

    - name: Get Kube Manifests
      run: echo "::set-output name=manifestsBundle::$(find ./kube -type f -name '*.yaml')"
      id: kube_manifests
    - uses: Azure/k8s-deploy@v1
      with:

        manifests: |
         ${{ steps.kube_manifests.outputs.manifestsBundle }}
        # ${{ steps.bake_octoprint.outputs.manifestsBundle }}
        # ${{ steps.bake_seedbox.outputs.manifestsBundle }}
