# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: Azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - name: Generate
      run: ./generate.sh

    - name: Apply
      run: kubectl apply -f kube
